### ISSUE TITLE
error : task: non-zero exit (1)

### ISSUE THREAD

**Issue by tony-Ma-yami** [portainer/portainer-compose#16]
我使用docker stack deploy启动时会报错task: non-zero exit (1), 但是我使用docker run 的方式启动则不会有问题.  我的compose文件如下:
portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /home/portainer/data:/data
    networks:
      - mynet
    deploy:
      placement:
        constraints: [node.role==manager]

**Comment by ran-dall** [comment]
@tony-Ma-yami I was getting this issue. It turned out that I didn't have a `/opt` directory in `root` directory. I decided to simply change the `docker-compose` to a local directory. That fixed the problem.

So this is what my file looks like...

```yaml
version: '2'

services:
  proxy:
    build: nginx/
    container_name: "portainer-proxy"
    ports:
      - "80:80"
    networks:
      - local

  templates:
    image: portainer/templates
    container_name: "portainer-templates"
    networks:
      - local

  portainer:
    image: portainer/portainer
    restart: always
    container_name: "portainer-app"
#Automatically choose 'Manage the Docker instance where Portainer is running' by adding <-> to the command
    command: --templates http://templates/templates.json
             --host=unix:///var/run/docker.sock
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-compose/data:/data

  watchtower:
    image: v2tec/watchtower
    container_name: "portainer-watchtower"
    command: --cleanup portainer-app portainer-watchtower portainer/templates
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  local:
    driver: bridge
```
