### ISSUE TITLE
404 for Api only with Traefik compose

### ISSUE THREAD

**Issue by galuspeed** [portainer/portainer-compose#22]
The following configuration will deploy, however the api calls are all 404. I'm not sure why this happens, maybe someone can offer me some insight?

Below is the portainer compose file.
```yaml

version: '3'

networks:
  web:
    external: true
      
services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    restart: unless-stopped
    networks:
      - web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $HOME/Documents/services:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`portainer.gluaxspeed.xyz`)"
      - "traefik.http.routers.portainer.entrypoints=http"
      - "traefik.docker.network=web"
```

Below is traefik configurations.
```yaml

version: '3'
  
networks:
  web:
    external: true

services:
  traefik:
    container_name: traefik
    image: traefik:v2.2
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    networks:
      - web
    volumes:
      - $HOME/Documents/services/traefik.yml:/traefik.yml
      - $HOME/Documents/services/dynamic_conf.yml:/dynamic_conf.yml
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`monitor.gluaxspeed.xyz`)"

  whoami:
    image: containous/whoami
    container_name: whoami
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.gluaxspeed.xyz`)"
```
Traefik.yml
```yaml

log:
  level: INFO

entryPoints:
  http:
    address: :80

api:
  insecure: false
  debug: true
  dashboard: true

providers:
  docker:
    exposedByDefault: false
    network: web
  file:
    filename: dynamic_conf.yml
    watch: true

accessLog: {}
```

dynamic_conf.yml
```yaml

http:
  routers:
    my-api:
      entryPoints:
        - http
      rule: "PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
      service: api@internal
      middlewares:
        - dashboard-auth

  middlewares:
    dashboard-auth:
      basicAuth:
        users:
          - redacted

    https-redirect:
      redirectScheme:
        scheme: https
```
