### ISSUE TITLE
Use Traefik for Edge Agent service

### ISSUE THREAD

**Issue by robdyke** [portainer/portainer-compose#24]
Portainer communicates with the edge agent over port 8000 (as per [Edge Agent Guide](https://downloads.portainer.io/edge_agent_guide.pdf))

The example Traefik docker-compose does not expose :8000.

As Traefik can proxy any TCP traffic, let's use it?

**Comment by xe-nvdk** [comment]
Hi. No need to expose 8000. When you set up the Edge agent, you need to change the Portainer server URL to match the Edge entry point.

**Comment by robdyke** [comment]
Hummmm. So I set https://domain.tld in the config by the edge agent complained that it couldn't reach ws://endpoint on :8000 although it could reach the https:// on :443

**Comment by xe-nvdk** [comment]
When you add an edge agent, you need to change the Portainer server's URL to point edge.yourdomain.com. With the current configuration, with any request that came for that URL, Traefik will take and redirect to the port 800 in the container. 

Take note that you need to specify one URL for portainer UI that works in port 9000 and another URL for edge. 

Anyway, your proposal is valid, so, please, write in a new file to have both alternatives available. 

Thank you again for your contribution is very appreciated. 
Ignacio

**Comment by robdyke** [comment]
Thanks and will do

**Comment by baskinsy** [comment]
I probably have the same issue or missing something. I have deployed portainer with compose and I have a resolvable second URL (edge.mydomain.com) but edge agents are unable to connect with the following ERROR:

```
2020/12/22 15:04:25 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: short poll request failed]
2020/12/22 15:04:30 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: short poll request failed]
2020/12/22 15:04:35 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: short poll request failed]
2020/12/22 15:04:40 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: short poll request failed]
```

Edge URL is set when creating the edge endpoint as https://edge.mydomain.com and it is listening but the edge agent refuses to associate. My understanding was that proxying 8000 port with traefik on the separate URL is enough.

**Comment by robdyke** [comment]
Paste me the logs from Portainer && agent side @baskinsy

**Comment by baskinsy** [comment]
The only log on edge side is the above, on portainer side logs are not displaying anything at all. I made a clean test again to verify that and the only log I can find is the above ERROR on egde agent side....

**Comment by baskinsy** [comment]
I think the tokens are broken somehow. I get "Incorrect padding" when i try to decode the token copied from portainer here https://www.base64code.com/decode

**Comment by robdyke** [comment]
@baskinsy I had those errors when using the provided docker-compose. I opened :8000 direct to portainer and the agent connected. Try the compose file that proxies agent through Traefik

**Comment by baskinsy** [comment]
Yes I read your proposal to proxy also 8000 but then is the communication secured? I would try it but that means the provided docker-compose does not work for edge agents as it seems.

**Comment by robdyke** [comment]
@baskinsy the ws:// on :8000 is (as I understand) encrypted

**Comment by baskinsy** [comment]
Found the issue and was confirmed by a staff member on slack. The KEY generation is broken in my case due to I'm using a four level domain for URL (edge.staging.mydomain.com).

https://github.com/portainer/portainer/issues/4647

**Comment by robdyke** [comment]
Glad yr sorted. Opened an issue upsteam? I often use four.level.doma.is

**Comment by baskinsy** [comment]
Yes seems the KEY cannot be decoded when a four level URL is used. When IP is used the decode works. I'll redeploy tomorrow with a third level URL on edge traefic vhost and report back if it works.

**Comment by hSinding** [comment]
@baskinsy Did you get it to work with a third level URL?
When i'm trying to decode my KEY i'm getting Incorrect padding aswell, but with an IP it works.

xxxx.mydomain.com

**Comment by baskinsy** [comment]
@hSinding Yes I had success on decoding a KEY with a third level domain but I have still issues to connect the edge agent, it is correctly added and registered but cannot be browsed. Although the KEY issue can be circumvent with a third level domain, at least for me.

**Comment by reinoldus** [comment]
Same issue here, edge just won't connect:

```
2021/03/17 13:09:08 [ERROR] [internal,edge,poll] [message: an error occured during short poll] [error: Get https://edge1.domain.com/api/endpoints/5/status: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)]
```

But it seems to be a traefik misconfiguration because when I call the api endpoint manually I get 404

**Comment by charnesp** [comment]
With a small hack I was able to make it work through Traefik : 

Portainer is setup in Traefik with : 

```
      # Frontend
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-portainer.rule=Host(`portainer.mydomain.com`)"
      - "traefik.http.services.frontend-portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.frontend-portainer.service=frontend-portainer"
      - "traefik.http.routers.frontend-portainer.tls.certresolver=lets-encrypt"

      # Edge
      - traefik.http.routers.edge-portainer.rule=Host(`edge.mydomain.com`)
      - traefik.http.services.edge-portainer.loadbalancer.server.port=8000
      - traefik.http.routers.edge-portainer.service=edge-portainer
      - traefik.http.routers.edge-portainer.tls.certresolver=lets-encrypt
      - traefik.http.middlewares.edge-portainer-redirect.redirectregex.regex=^http://(.*)
      - traefik.http.middlewares.edge-portainer-redirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.http.middlewares=edge-portainer-redirect
      - traefik.http.services.http.loadbalancer.server.port=80
```

You first need to decode the EDGE_KEY (using https://www.base64decode.org for example) in order to obtain the fingerprint and the endpoint ID.

You should obtain something like: `https://edge.mydomain.com|edge.mydomain.com:8000|aa:bb:cc:dd:ee:ff:00:00:00:01:00:00:00:00:00:00|3`

3 being the endpoint ID, `aa:bb:cc:dd:ee:ff:00:00:00:01:00:00:00:00:00:00` being the server fingerprint.

I modified it like that : `https://portainer.mydomain.com|https://edge.mydomain.com|aa:bb:cc:dd:ee:ff:00:00:00:01:00:00:00:00:00:00|3`
 
and used https://www.base64encode.org (with URL-safe encoding enabled) to regenerate the key. 
Then simply use this generated EDGE_KEY on the agent and it should work without exposing any `8000`port

**Comment by alackmann** [comment]
@charnesp this was such a handy tip. Many thanks. Portainer-peeps - it'd be fantastic to be able to generate an EDGE_KEY from the UI that supports this configuration. At very least an additional (optional) field for the edge URL would help.

**Comment by BerkeleyTrue** [comment]
@charnesp Thanks for the help.

I'd like to add I had to add an extra step. With the new key, it complained about a deprecated MD5 fingerprint so I had to update it with a SHA256 fingerprint. No idea why.

![image](https://user-images.githubusercontent.com/6775919/163311260-70787eac-0d66-4256-9747-1b42c4f53a51.png)

This really needs to be an option in the UI, or at least update the docs so it's not point edge as a separate url that doesn't work without the 8000 port open.

**Comment by mfruhner** [comment]
Hello, I am currently trying to achieve the same: Manage an Edge Agent in a VM via Portainer behind Traefik running in WSL. 

As i described [here](https://github.com/portainer/portainer/issues/5218#issuecomment-1109479528), I try to browse an Edge Agent after successful association. The request to open the tunnel connection however goes to 127.0.0.1 and the connection fails.. Any advice?

**Comment by Xosten** [comment]
> With a small hack I was able to make it work through Traefik :
> 
> Portainer is setup in Traefik with :
> 
> ```
>       # Frontend
>       - "traefik.enable=true"
>       - "traefik.http.routers.frontend-portainer.rule=Host(`portainer.mydomain.com`)"
>       - "traefik.http.services.frontend-portainer.loadbalancer.server.port=9000"
>       - "traefik.http.routers.frontend-portainer.service=frontend-portainer"
>       - "traefik.http.routers.frontend-portainer.tls.certresolver=lets-encrypt"
> 
>       # Edge
>       - traefik.http.routers.edge-portainer.rule=Host(`edge.mydomain.com`)
>       - traefik.http.services.edge-portainer.loadbalancer.server.port=8000
>       - traefik.http.routers.edge-portainer.service=edge-portainer
>       - traefik.http.routers.edge-portainer.tls.certresolver=lets-encrypt
>       - traefik.http.middlewares.edge-portainer-redirect.redirectregex.regex=^http://(.*)
>       - traefik.http.middlewares.edge-portainer-redirect.redirectregex.replacement=https://$${1}
>       - traefik.http.routers.http.middlewares=edge-portainer-redirect
>       - traefik.http.services.http.loadbalancer.server.port=80
> ```
> 
> You first need to decode the EDGE_KEY (using https://www.base64decode.org for example) in order to obtain the fingerprint and the endpoint ID.
> 
> You should obtain something like: `https://edge.mydomain.com|edge.mydomain.com:8000|aa:bb:cc:dd:ee:ff:00:00:00:01:00:00:00:00:00:00|3`
> 
> 3 being the endpoint ID, `aa:bb:cc:dd:ee:ff:00:00:00:01:00:00:00:00:00:00` being the server fingerprint.
> 
> I modified it like that : `https://portainer.mydomain.com|https://edge.mydomain.com|aa:bb:cc:dd:ee:ff:00:00:00:01:00:00:00:00:00:00|3`
> 
> and used https://www.base64encode.org (with URL-safe encoding enabled) to regenerate the key. Then simply use this generated EDGE_KEY on the agent and it should work without exposing any `8000`port

Hello,

I'm having the same issue and tried your fix but I'm encountering the following error : 
```
portainer             | time="2022-05-29T21:11:32Z" level=info msg="2022/05/29 21:11:32 http error: Unable to find an environment with the specified identifier inside the database (err=object not found inside the database) (code=404)"
portainer_edge_agent  | 2022/05/29 21:11:32 [ERROR] [edge] [message: an error occured during short poll] [error: short poll request failed]
```
This is my docker-compose, do you have any ideas please on how I could fix it? I'm running Portainer 2.13.1.
```
version: "3.3"

services:
  portainer:
    networks:
      - web
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    restart: always
    container_name: portainer
    ports:
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    labels:
      # Frontend
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer02.XXXXXX.YY`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.services.portainer.loadbalancer.server.port=9000
      - traefik.http.routers.portainer.service=portainer
      - traefik.http.routers.portainer.tls.certresolver=lets-encrypt

  portainer_edge_agent:
    image: portainer/agent:2.13.1
    container_name: portainer_edge_agent
    restart: unless-stopped
    networks:
      - web
    environment:
      - EDGE=1
      - EDGE_ID=a2094540-XXXXX-XXXXXXX-XXXXXX-f109cfe0b0b9
      - EDGE_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
      - EDGE_INSECURE_POLL=1
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '/var/lib/docker/volumes:/var/lib/docker/volumes'
      - '/:/host'
      - './portainer_agent_data:/data'
    labels:
      # Edge
      - traefik.http.routers.edge-portainer.rule=Host(`edge2.XXXXXX.YY`)
      - traefik.http.routers.edge-portainer.entrypoints=websecure
      - traefik.http.services.edge-portainer.loadbalancer.server.port=8000
      - traefik.http.routers.edge-portainer.service=edge-portainer
      - traefik.http.routers.edge-portainer.tls.certresolver=lets-encrypt
      - traefik.http.middlewares.edge-portainer-redirect.redirectregex.regex=^http://(.*)
      - traefik.http.middlewares.edge-portainer-redirect.redirectregex.replacement=https://$${1}
      - traefik.http.routers.http.middlewares=edge-portainer-redirect
      - traefik.http.services.http.loadbalancer.server.port=80


volumes:
  portainer_data:

networks:
  web:
    external: true
```
