### ISSUE TITLE
Hiding portainer containers in portainer-compose

### ISSUE THREAD

**Issue by evsasha** [portainer/portainer-compose#5]
How hiding in portainer-compose?

Labels in docker-compose.yml like:
```
    labels:
      owner: "acme"
```
don't work.

**Comment by deviantony** [comment]
You'll need to use the `-l` flags according to the docs here: https://portainer.readthedocs.io/en/latest/configuration.html#hiding-specific-containers


So update the `docker-compose.yml` file with the following content for the portainer definition:

 ```yml
  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    command: --templates http://templates/templates.json -d /data -l owner=portainer
    networks:
      - local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
    labels:
      owner: "portainer"
```
