### ISSUE TITLE
404 not found after running docker-compose

### ISSUE THREAD

**Issue by waspinator** [portainer/portainer-compose#8]
Do I need to do any additional configuration before running docker-compose, or should I be able to just clone and run? 

```
CONTAINER ID        IMAGE                    COMMAND                  CREATED             STATUS              PORTS                         NAMES
968ce00d527a        centurylink/watchtower   "/watchtower --cle..."   2 minutes ago       Up 12 seconds                                     portainer-watchtower
348e571e2f04        portainer/portainer      "/portainer --temp..."   2 minutes ago       Up 12 seconds       9000/tcp                      portainer-app
4832846df683        portainercompose_proxy   "nginx -g 'daemon ..."   2 minutes ago       Up 11 seconds       0.0.0.0:80->80/tcp, 443/tcp   portainer-proxy
40388cb90c8d        portainer/templates      "nginx -g 'daemon ..."   2 minutes ago       Up 12 seconds       80/tcp, 443/tcp               portainer-templates
```

editing the `docker-compose.yaml` file to this makes it work. But I feel I'm missing out on something without those other containers running.

```
version: '2'

services:

  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/portainer/data:/data
```
